accounts/urls.py
from django.contrib.auth.views import (
    LoginView,
    login,
    logout,
    password_reset,
    password_reset_complete,
    password_reset_confirm,
    password_reset_done,
)
from django.urls import path, re_path

from .views import (
    ChangePasswordView,
    EditProfileView,
    EditUserProfile,
    ProfileView,
    RegisterView,
)

app_name = "accounts"

urlpatterns = [
    re_path(r"^(?P<pk>\d+)/$", ProfileView.as_view(), name="view_profile_with_pk"),
    re_path(r"^(?P<pk>\d+)/edit$", EditUserProfile.as_view(), name="EditUserProfile"),
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", login, {"template_name": "accounts/login.html"}, name="login"),
    path("logout/", logout, {"template_name": "accounts/logout.html"}, name="logout"),
    path("edit/", EditProfileView.as_view(), name="edit_profile"),
    path("change-password/", ChangePasswordView.as_view(), name="change_password"),
    path(
        "reset-password/",
        password_reset,
        {
            "template_name": "accounts/reset_password.html",
            "post_reset_redirect": "accounts:password_reset_done",
            "email_template_name": "accounts/reset_password_email.html",
        },
        name="reset_password",
    ),
    path(
        "reset-password/done/",
        password_reset_done,
        {"template_name": "accounts/reset_password_done.html"},
        name="password_reset_done",
    ),
    re_path(
        r"reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$",
        password_reset_confirm,
        {
            "template_name": "accounts/reset_password_confirm.html",
            "post_reset_redirect": "accounts:password_reset_complete",
        },
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        password_reset_complete,
        {"template_name": "accounts/reset_password_complete.html"},
        name="password_reset_complete",
    ),
]

mainapp/urls.py
from django.urls import path, re_path

from .views import (
    ArticleDetailView,
    ArticleEditView,
    CategoryDetailView,
    CommentEditView,
    CommentSavingView,
    HotArticleImageView,
    MainListView,
    UserMarkedSomethingView,
    UserRepostArticleView,
)

app_name = "main"

urlpatterns = [
    path("add_comment/", CommentSavingView.as_view(), name="add-comment"),
    path("hot-image-view/", HotArticleImageView.as_view(), name="get-hot-image"),
    path(
        "user-repost-article/",
        UserRepostArticleView.as_view(),
        name="user-repost-article",
    ),
    path(
        "user-marked-something/",
        UserMarkedSomethingView.as_view(),
        name="user-marked-something",
    ),
    path("", MainListView.as_view(), name="home"),
    re_path(
        r"^(?P<slug>[-\w]+)/$", CategoryDetailView.as_view(), name="category-detail"
    ),
    re_path(
        r"^comment/(?P<slug>[-\w]+)/(?P<id>\d+)/edit$",
        CommentEditView.as_view(),
        name="comment-edit",
    ),
    re_path(
        r"^(?P<cat_slug>[-\w]+)/(?P<slug>[-\w]+)/$",
        ArticleDetailView.as_view(),
        name="article-detail",
    ),
    re_path(
        r"^(?P<cat_slug>[-\w]+)/(?P<slug>[-\w]+)/edit$",
        ArticleEditView.as_view(),
        name="article-edit",
    ),
    re_path(
        r"^(?P<cat_slug>[-\w]+)/(?P<slug>[-\w]+)/$",
        ArticleDetailView.as_view(),
        name="article-detail",
    ),
]

mainapp/forms.py
from django import forms

from .models import Article, Comment


class CommentForm(forms.Form):

    comment = forms.CharField(widget=forms.Textarea)


class ArticleEdit(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "content", "image"]


class CommentEditForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]


class RepostForm(forms.Form):
    repost_comment = forms.CharField(widget=forms.Textarea)


class ArticleForm(forms.ModelForm):
    content = forms.CharField(
        widget=forms.Textarea(
            attrs={"class": "form-control", "placeholder": "Write about it..."}
        )
    )

    class Meta:
        model = Article
        fields = ("title", "content", "image")

    def save(self, user, category):
        article = super(ArticleForm, self).save(commit=False)
        article.author = user
        article.category = category
        article.save()

        return article

mainapp/views.py
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Count
from django.http import Http404
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.dateformat import DateFormat, TimeFormat
from django.utils.decorators import method_decorator
from django.utils.formats import get_format
from django.views import View
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from .forms import ArticleEdit, ArticleForm, CommentEditForm, CommentForm, RepostForm
from .mixins import CategoryListMixin
from .models import Article, Category, Comment, Mark, Repost


class MainListView(ListView):

    template_name = "mainapp/home.html"
    model = Article

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(MainListView, self).get_context_data()
        context["hot_articles"] = self.model.objects.all().order_by("-id")[:4]
        context["popular_articles"] = self.model.objects.all().order_by("-id")[4:6]
        context["articles_count_enough"] = self.model.objects.all().count() > 3
        print(context["articles_count_enough"])
        if context["articles_count_enough"]:
            context["last_article_image"] = context["hot_articles"][3].image.url
        context["categories"] = Category.objects.all()
        return context


class CategoryDetailView(DetailView, CategoryListMixin):

    template_name = "mainapp/category_detail.html"
    model = Category

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoryDetailView, self).get_context_data()
        context["category"] = self.get_object()
        context["articles"] = self.get_object().article_set.all()
        context["article_form"] = ArticleForm()
        return context

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = ArticleForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            user = request.user
            category = self.get_object()
            article = form.save(user, category)
            return redirect(article.get_absolute_url())
        context = super(CategoryDetailView, self).get_context_data()
        context["category"] = self.get_object()
        context["articles"] = self.get_object().article_set.all()
        context["article_form"] = form
        return context


class ArticleEditView(LoginRequiredMixin, TemplateView):

    template_name = "mainapp/article_edit.html"

    def get(self, request, *args, **kwargs):
        article = Article.objects.get(slug=kwargs["slug"])
        if request.user != article.author:
            return Http404
        form = ArticleEdit(instance=article)
        path = request.path.split("/")
        args = {"form": form, "cat_slug": path[1], "slug": path[2]}
        return render(request, self.template_name, args)

    def post(self, request, *args, **kwargs):
        article = Article.objects.get(slug=kwargs["slug"])
        if request.user != article.author:
            return Http404
        form = ArticleEdit(request.POST, request.FILES, instance=article)
        if form.is_valid():
            form.save()

            return redirect(article.get_absolute_url())
        args = {"form": form}
        return render(request, self.template_name, args)


class CommentEditView(LoginRequiredMixin, TemplateView):

    template_name = "mainapp/comment_edit.html"

    def get(self, request, *args, **kwargs):
        id_comment = kwargs["id"]
        slug = kwargs["slug"]
        comment = Comment.objects.get(id=kwargs["id"])
        if request.user != comment.author:
            return Http404
        form = CommentEditForm(instance=comment)
        args = {"form": form, "id_comment": id_comment, "slug": slug}
        return render(request, self.template_name, args)

    def post(self, request, *args, **kwargs):
        article = Article.objects.get(slug=kwargs["slug"])
        comment = Comment.objects.get(id=kwargs["id"])
        if request.user != comment.author:
            return Http404
        form = CommentEditForm(request.POST, request.FILES, instance=comment)
        if form.is_valid():
            form.save()
            return redirect(article.get_absolute_url())
        args = {"form": form}
        return render(request, self.template_name, args)


class ArticleDetailView(DetailView, CategoryListMixin):

    template_name = "mainapp/article_detail.html"
    model = Article

    def get_context_data(self, *, object_list=None, **kwargs):
        path = self.request.path.split("/")
        context = super(ArticleDetailView, self).get_context_data()
        context["article"] = self.get_object()
        context["article_comments"] = (
            self.get_object().comments.all().order_by("-timestamp")
        )
        context["comment_form"] = CommentForm()
        context["repost_form"] = RepostForm()
        # context['article_reposts'] = self.get_object().reposts.all().count()  # NEED IMPROVE
        article_reposts = (
            self.get_object()
            .reposts.values("content")
            .all()
            .annotate(repost_count=Count("content_type"))
        )
        article_repost_count = 0
        for article_repost in article_reposts:
            article_repost_count += article_repost["repost_count"]
        context["article_reposts"] = article_repost_count
        context["cat_slug"] = path[1]
        context["slug"] = path[2]
        return context


class HotArticleImageView(View):
    def get(self, request, *args, **kwargs):
        article_id = request.GET.get("article_id")
        article = get_object_or_404(Article, id=article_id)
        data = {"article_image": article.image.url}
        return JsonResponse(data)


class CommentSavingView(LoginRequiredMixin, View):

    template_name = "mainapp/article_detail.html"

    def post(self, request, *args, **kwargs):
        article_id = self.request.POST.get("article_id")
        comment = self.request.POST.get("comment")
        article = Article.objects.get(pk=article_id)
        new_comment = article.comments.create(author=request.user, content=comment)
        likes_count = new_comment.get_likes()
        dislikes_count = new_comment.get_dislikes()
        dt = datetime.now()
        df = DateFormat(dt)
        tf = TimeFormat(dt)
        new_comment_timestamp = (
            df.format(get_format("DATE_FORMAT"))
            + ", "
            + tf.format(get_format("TIME_FORMAT"))
        )
        data = [
            {
                "author": new_comment.author.get_full_name(),
                "comment": new_comment.content,
                "comment_id": new_comment.pk,
                "comment_likes": likes_count,
                "comment_dislikes": dislikes_count,
                "timestamp": new_comment_timestamp,
                "slug": article.slug,
            }
        ]
        return JsonResponse(data, safe=False)


class UserRepostArticleView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        article_id = self.request.POST.get("article_id")
        comment = self.request.POST.get("comment")
        if not article_id:
            data = {"status": "FATAL"}
            return JsonResponse(data)
        article = Article.objects.get(pk=article_id)
        if not article:
            data = {"status": "FATAL"}
            return JsonResponse(data)
        article.reposts.create(author=request.user, content=comment or "")
        article_reposts = article.reposts.all().count()
        data = {"article_reposts": article_reposts}
        return JsonResponse(data)


class UserMarkedSomethingView(View):

    model = None
    model_obj = None
    model_mark = Mark

    def get(self, request, *args, **kwargs):
        author = request.user
        mark = self.request.GET.get("mark")
        obj_id = self.request.GET.get("obj_id")
        model_type = self.request.GET.get("model_type")
        ct = ContentType.objects.get(model=model_type)
        self.model = ct.model_class()
        self.model_obj = self.model.objects.get(pk=obj_id)

        mark = mark.upper()
        if mark in ("D", "L", "DISLIKE", "LIKE"):
            try:
                mark_obj = self.model_obj.marks.get(author=author)
                if (mark_obj.object_id == int(obj_id)) and (
                    mark_obj.content_type.model_class() == self.model
                ):
                    mark_obj.delete_or_switch(mark)
            except ObjectDoesNotExist:
                self.model_obj.marks.create(author=request.user, status=mark[0])
            likes_count = self.model_mark.get_related_likes(model_obj=self.model_obj)
            dislikes_count = self.model_mark.get_related_dislikes(
                model_obj=self.model_obj
            )
            data = {
                "obj_id": obj_id,
                "obj_likes": likes_count,
                "obj_dislikes": dislikes_count,
                "model_type": model_type,
                "status": "OK",
            }
            return JsonResponse(data)

templates/mainapp/article_create.html
{% extends 'base.html' %}

{% block content %}
{% endblock content %}

templates/mainapp/article_detail.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
<title>{{ article.title }}</title>
{% endblock title %}

{% block content %}
<main role="main" class="container">
  <div class="row">
    <div class="col-md-8 blog-main">
      <h3 class="pb-3 mb-4 font-italic border-bottom">
        View all articles about
        <a href="{{ article.category.get_absolute_url }}">{{ article.category.name }}</a>
      </h3>

      <div class="blog-post">
        <h2 class="blog-post-title">{{ article.title }}</h2>
        <p class="blog-post-meta">January 1, 2014 by <a href="#">{{ article.author }}</a></p>

        <p><img src="{{ article.image.url }}" alt="" style="widht:100%; height:500px"></p>
        <p>{{ article.content }}</p>
        {% if article.author == request.user %}
          <a class="btn btn-success" href="{% url "main:article-edit" cat_slug=cat_slug slug=slug %}">Edit article</a>
        {% endif %}
        <hr>
      <div class="container">
          <div class="col-sm-12">
              <a href="#" class="like" data-id="{{ article.pk }}" data-type="article"><i class="far fa-thumbs-up" style="color: #00cc00"></i></a><span id="article-liked-{{ article.pk }}">{{ article.get_likes }}</span>
              <a href="#" class="dislike" data-id="{{ article.pk }}" data-type="article" style="padding-left: 25px"><i class="far fa-thumbs-down" style="color: #a41515"></i></a><span id="article-disliked-{{ article.pk }}">{{ article.get_dislikes }}</span>
              <a href="#" id="repost" data-type="article" style="padding-left: 25px" data-toggle="modal" data-target="#repostModal"><i class="fas fa-share" style="color: #6f42c1"></i></a><span id="reposted">{{ article_reposts }}</span>

            <!-- Modal -->

            <div class="modal fade" id="repostModal" tabindex="-1" role="dialog" aria-labelledby="repostModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="repostModalLabel">What do u think about it..?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>

                  <div class="modal-body">
                    <div class="modal-body">
                        {% if request.user.is_authenticated %}
                        <form action="POST">
                            {% csrf_token %}
                            {{ repost_form|crispy }}
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary" id="add_repost">Continue</button>
                        </form>
                        {% else %}
                            <h2 class="alert alert-info">If you want to repost any article, you must be registered</h2>
                        {% endif %}
                    </div>
                  </div>
                </div>
              </div>
            </div>

              <hr>
              <div class="col-sm-7 col-sm-offset-2">
                  <h6>Comments:</h6>
                  {% if request.user.is_authenticated %}
                      <form action="" method="post">
                          <input type="hidden" id="article" data-id="{{ article.pk }}">
                          {% csrf_token %}
                          {{ comment_form|crispy }}
                          <input type="submit" value="Post" id="add_comment">
                      </form>
                  {% else %}
                      <h2 class="alert alert-info">If you want to add comments, you must be registered</h2>
                  {% endif %}
                  <div class="comments">
                  {% for comment in article_comments %}
                  <div class="col-sm-12">
                    <hr>
                      <div class="d-flex justify-content-between bd-highlight mb-3">
                          <div class="p-2 bd-highlight">
                            <small>{{ comment.author.get_full_name }}</small>
                            <p>{{ comment.content }}</p>
                            <small>{{ comment.timestamp }}</small>
                            <br>
                            {% if request.user == comment.author %}
                              <a class="btn btn-success btn-sm" href="{% url "main:comment-edit" id=comment.id slug=slug %}">Edit comment</a>
                            {% endif %}
                          </div>
                          {% if request.user.is_authenticated %}
                          <div class="p-2 bd-highlight justify-content-end">
                            <a href="#" class="like" data-id="{{ comment.pk }}" data-type="comment"><i class="far fa-thumbs-up" style="color: #00cc00"></i></a><span id="comment-liked-{{ comment.pk }}">{{ comment.get_likes }}</span>
                            <a href="#" class="dislike" data-id="{{ comment.pk }}" data-type="comment" style="padding-left: 25px"><i class="far fa-thumbs-down" style="color: #a41515"></i></a><span id="comment-disliked-{{ comment.pk }}">{{ comment.get_likes }}</span>
                          </div>
                          {% endif %}
                      </div>
                  </div>
                  {% endfor %}
                  </div>
              </div>
          </div>
      </div>
      </div>
    </div>
  </div>
</main>
{% endblock content %}

{% block jquery %}
<script>
    $(document).ready(function () {
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        var csrftoken = getCookie('csrftoken');
        $('#add_comment').on('click', function (e) {
            e.preventDefault();
            {% if request.user.is_authenticated %}
            var article_id = $('#article').attr('data-id');
            var comment = $('#id_comment').val();

            data = {
                article_id: article_id,
                comment: comment,
                csrfmiddlewaretoken: csrftoken
            };

            $.ajax({
                type: "POST",
                url: "{% url 'main:add-comment' %}",
                data: data,
                dataType: 'json',
                success: function (data) {
                    var edit_url = "{% url "main:comment-edit" id=1 slug='aaaaa' %}".replace(/1/, data[0]['comment_id']).replace(/aaaaa/, data[0]['slug']);
                    $.each(data, function (field) {
                        $('.comments').prepend(`<div class="col-sm-12"><hr>`+
                        `<div class="d-flex justify-content-between bd-highlight mb-3">`+
                        `<div class="p-2 bd-highlight"><small>`+data[field]['author']+`</small><p>`+data[field]['comment']+
                        `</p><small>`+data[field]['timestamp']+`</small><a class="btn btn-success btn-sm" href="`+edit_url+`">Edit comment</a></div>`+
                        `</p><small>`+data[field]['timestamp']+`</small></div>`+
                        `<div class="p-2 bd-highlight justify-content-end">`+
                        `<a href="#" class="like" data-id="`+data[field]['comment_id']+`" data-type="comment">`+
                        `<i class="far fa-thumbs-up" style="color: #00cc00"></i>`+
                        `</a><span id="comment-liked-`+data[field]['comment_id']+`">`+data[field]['comment_likes']+`</span>`+
                        `<a href="#" class="dislike" data-id="`+data[field]['comment_id']+`" data-type="comment" style="padding-left: 25px">`+
                        `<i class="far fa-thumbs-down" style="color: #a41515"></i>`+
                        `</a><span id="comment-disliked-`+data[field]['comment_id']+`">`+data[field]['comment_dislikes']+`</span>`+
                        `</div></div></div>`);
                        $('#id_comment').val('');
                    })
                }
            });
            {% endif %}
        });
        $('#add_repost').on('click', function (e) {
            e.preventDefault();
            {% if request.user.is_authenticated %}
            var article_id = $('#article').attr('data-id');
            var comment = $('#id_repost_comment').val();

            data = {
                article_id: article_id,
                comment: comment,
                csrfmiddlewaretoken: csrftoken
            };

            $.ajax({
                type: "POST",
                url: "{% url 'main:user-repost-article' %}",
                data: data,
                dataType: "json",
                success: function (data) {
                    $('#reposted').html(data.article_reposts);
                }
            });
            {% endif %}
        });
    })
</script>
<script>
    $(document).ready(function () {
        $('.like').click(function (e) {
            e.preventDefault();
            {% if request.user.is_authenticated %}
            var mark = 'L';
            var obj_id = $(this).attr('data-id');
            var model_type = $(this).attr('data-type');

            data = {
                mark: mark,
                obj_id: obj_id,
                model_type: model_type
            };

            $.ajax({
                type: "GET",
                url: "{% url 'main:user-marked-something' %}",
                data: data,
                dataType: "json",
                success: function (data) {
                    console.log(data);
                    $('#'+data.model_type+'-liked-'+data.obj_id).html(data.obj_likes);
                    $('#'+data.model_type+'-disliked-'+data.obj_id).html(data.obj_dislikes);
                }
            })
            {% endif %}
        });
        $('.dislike').click(function (e) {
            e.preventDefault();
            {% if request.user.is_authenticated %}
            var mark = 'D';
            var obj_id = $(this).attr('data-id');
            var model_type = $(this).attr('data-type');

            data = {
                mark: mark,
                obj_id: obj_id,
                model_type: model_type
            };

            $.ajax({
                type: "GET",
                url: "{% url 'main:user-marked-something' %}",
                data: data,
                dataType: "json",
                success: function (data) {
                    console.log(data);
                    $('#'+data.model_type+'-liked-'+data.obj_id).html(data.obj_likes);
                    $('#'+data.model_type+'-disliked-'+data.obj_id).html(data.obj_dislikes);
                }
            })
            {% endif %}
        });
    })
</script>
{% endblock jquery %}

templates/mainapp/article_edit.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                <form action="{% url 'main:article-edit' cat_slug=cat_slug slug=slug %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="submit">
                </form>
                <br>
            </div>
        </div>
    </div>
{% endblock content %}

templates/mainapp/article_form.html
{% extends 'base.html' %}

{% block title %}
<title>Create Article</title>
{% endblock title %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form method="" action="">
                        {% csrf_token %}
                        {{ form }}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/mainapp/category_detail.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
<title>{{ category.name }}</title>
{% endblock title %}

{% block content %}
    <main role="main" class="container">
        <div class="d-flex justify-content-between bd-highlight mb-3">
          <div class="p-2 bd-highlight">
            <h2>{{ category.name|upper }}</h2>
          </div>
          <div class="p-2 bd-highlight justify-content-end">
{#            <a href="{% url 'main:article-create' %}" class="btn btn-primary">Add Article</a>#}
              {% if request.user.is_authenticated %}
                  <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bd-example-modal-lg">
                      Add Article
                  </button>
              {% else %}
                  <a class="btn btn-sm btn-outline-secondary" href="{% url 'accounts:login' %}">Sign in</a> to add article
              {% endif %}
          </div>
        </div>

        <!-- Modal -->
        <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-lg">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ article_form|crispy }}
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Continue</button>
                </form>
              </div>
            </div>
          </div>
        </div>

        <hr>
        <br>
        <div class="row mb-2">
        {% for article in articles %}
        <div class="col-md-6">
          <div class="card flex-md-row mb-4 box-shadow h-md-250">
            <div class="card-body d-flex flex-column align-items-start">
              <strong class="d-inline-block mb-2 text-primary">{{ category.name }}</strong>
              <h3 class="mb-0">
                <a class="text-dark" href="{{ article.get_absolute_url }}">{{ article.title|truncatechars:20 }}</a>
              </h3>
              <div class="mb-1 text-muted">Nov 13</div>
              <p class="card-text mb-auto">{{ article.content|truncatewords:15 }}</p>
              <a href="{{ article.get_absolute_url }}">Continue reading</a>
            </div>
            <img class="card-img-right flex-auto d-none d-lg-block img-fluid img-preview image-preview"
                 src="{{ article.image.url }}" data-holder-rendered="true"
                 alt="Responsive image">
          </div>
        </div>
        {% endfor %}
        </div>
    </main>
{% endblock %}

templates/mainapp/comment_edit.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                <form action="{% url "main:comment-edit" id=id_comment slug=slug %}" method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="submit">
                </form>
            </div>
        </div>
    </div>
{% endblock content %}