accounts/urls.py
from django.contrib.auth.views import (
    LoginView,
    login,
    logout,
    password_reset,
    password_reset_complete,
    password_reset_confirm,
    password_reset_done,
)
from django.urls import path, re_path

from .views import (
    ChangePasswordView,
    EditProfileView,
    EditUserProfile,
    ProfileView,
    RegisterView,
)

app_name = "accounts"

urlpatterns = [
    re_path(r"^(?P<pk>\d+)/$", ProfileView.as_view(), name="view_profile_with_pk"),
    re_path(r"^(?P<pk>\d+)/edit$", EditUserProfile.as_view(), name="EditUserProfile"),
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", login, {"template_name": "accounts/login.html"}, name="login"),
    path("logout/", logout, {"template_name": "accounts/logout.html"}, name="logout"),
    path("edit/", EditProfileView.as_view(), name="edit_profile"),
    path("change-password/", ChangePasswordView.as_view(), name="change_password"),
    path(
        "reset-password/",
        password_reset,
        {
            "template_name": "accounts/reset_password.html",
            "post_reset_redirect": "accounts:password_reset_done",
            "email_template_name": "accounts/reset_password_email.html",
        },
        name="reset_password",
    ),
    path(
        "reset-password/done/",
        password_reset_done,
        {"template_name": "accounts/reset_password_done.html"},
        name="password_reset_done",
    ),
    re_path(
        r"reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$",
        password_reset_confirm,
        {
            "template_name": "accounts/reset_password_confirm.html",
            "post_reset_redirect": "accounts:password_reset_complete",
        },
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        password_reset_complete,
        {"template_name": "accounts/reset_password_complete.html"},
        name="password_reset_complete",
    ),
]

mainapp/urls.py
from django.urls import path, re_path

from .views import (
    ArticleDetailView,
    ArticleEditView,
    CategoryDetailView,
    CommentEditView,
    CommentSavingView,
    HotArticleImageView,
    MainListView,
    UserMarkedSomethingView,
    UserRepostArticleView,
)

app_name = "main"

urlpatterns = [
    path("add_comment/", CommentSavingView.as_view(), name="add-comment"),
    path("hot-image-view/", HotArticleImageView.as_view(), name="get-hot-image"),
    path(
        "user-repost-article/",
        UserRepostArticleView.as_view(),
        name="user-repost-article",
    ),
    path(
        "user-marked-something/",
        UserMarkedSomethingView.as_view(),
        name="user-marked-something",
    ),
    path("", MainListView.as_view(), name="home"),
    re_path(
        r"^(?P<slug>[-\w]+)/$", CategoryDetailView.as_view(), name="category-detail"
    ),
    re_path(
        r"^comment/(?P<slug>[-\w]+)/(?P<id>\d+)/edit$",
        CommentEditView.as_view(),
        name="comment-edit",
    ),
    re_path(
        r"^(?P<cat_slug>[-\w]+)/(?P<slug>[-\w]+)/$",
        ArticleDetailView.as_view(),
        name="article-detail",
    ),
    re_path(
        r"^(?P<cat_slug>[-\w]+)/(?P<slug>[-\w]+)/edit$",
        ArticleEditView.as_view(),
        name="article-edit",
    ),
    re_path(
        r"^(?P<cat_slug>[-\w]+)/(?P<slug>[-\w]+)/$",
        ArticleDetailView.as_view(),
        name="article-detail",
    ),
]

accounts/models.py
from django.conf import settings
from django.db import models

from mainapp.models import get_image_filename


class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    city = models.CharField(max_length=100, default="", blank=True, null=True)
    website = models.URLField(default="", blank=True, null=True)
    phone = models.IntegerField(default=0, blank=True, null=True)
    description = models.CharField(max_length=50, blank=True, null=True)
    avatar = models.ImageField(upload_to=get_image_filename, blank=True, null=True)

    def __str__(self):
        return self.user.username

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth.models import User

from .models import UserProfile


class RegistrationForm(UserCreationForm):

    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.email = self.cleaned_data["email"]

        if commit:
            user.save()

        return user


class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ("email", "first_name", "last_name", "password")


class EditUserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ["avatar"]

accounts/views.py
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import redirect, render
from django.views.generic import TemplateView

from mainapp.models import Repost

from .forms import EditProfileForm, EditUserProfileForm, RegistrationForm
from .models import UserProfile


class EditUserProfile(LoginRequiredMixin, TemplateView):

    template_name = "accounts/edituserprofile.html"

    def get(self, request, *args, **kwargs):
        form = EditUserProfileForm()

        args = {"form": form}
        return render(request, self.template_name, args)

    def post(self, request, *args, **kwargs):
        form = EditUserProfileForm(request.POST, request.FILES)
        if form.is_valid():
            user = UserProfile.objects.get(user=request.user)
            user.avatar = form.cleaned_data.get("avatar")
            user.save()
            return redirect("/")
        args = {"form": form}
        return render(request, self.template_name, args)


class RegisterView(TemplateView):

    template_name = "accounts/reg_form.html"

    def get(self, request, *args, **kwargs):
        form = RegistrationForm()
        args = {"form": form}
        return render(request, self.template_name, args)

    def post(self, request, *args, **kwargs):
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            UserProfile.objects.create(user=user)
            form.save()
            return redirect("/")
        args = {"form": form}
        return render(request, self.template_name, args)


class EditProfileView(LoginRequiredMixin, TemplateView):

    template_name = "accounts/edit_profile.html"

    def get(self, request, *args, **kwargs):
        form = EditProfileForm(instance=request.user)
        args = {"form": form}
        return render(request, "accounts/edit_profile.html", args)

    def post(self, request, *args, **kwargs):
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect("accounts:view_profile")


class ChangePasswordView(TemplateView):

    template_name = "accounts/change_password.html"

    def get(self, request, *args, **kwargs):
        form = PasswordChangeForm(user=request.user)
        args = {"form": form}
        return render(request, self.template_name, args)

    def post(self, request, *args, **kwargs):
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect("accounts:view_profile")
        else:
            return redirect("accounts:change_password")


class ProfileView(TemplateView):

    template_name = "accounts/profile.html"

    def get(self, request, *args, **kwargs):
        pk = kwargs.get("pk")
        user = User.objects.get(pk=pk)
        reposts = Repost.objects.filter(author=user).order_by("-timestamp")
        args = {"user": user, "reposts": reposts}
        return render(request, self.template_name, args)

templates/accounts/change_password.html
{% extends 'base.html' %}

{% block title %}

<title>Profile - Change Password</title>
{% endblock %}

{% block content %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
        <br>
    </form>
</div>
{% endblock content %}

templates/accounts/edit_profile.html
{% extends 'base.html' %}

{% block head %}

<title>Profile - Update Profile</title>
{% endblock %}

{% block content %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
        <br>
    </form>
</div>
{% endblock content %}

templates/accounts/edituserprofile.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <div class="row">
        <div class="col-2"></div>
        <div class="col-10">
            <form action="{% url "accounts:EditUserProfile" pk=request.user.id %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit">
            </form>
        </div>
    </div>

</div>
{% endblock content %}

templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
	<h1>Welcome</h1>
	<p>
		You can log in here!
	</p>
	<h2>login</h2>
	<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
	</form>
</div>
{% endblock content %}

templates/accounts/logout.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
	<h1>Logged out</h1>
	<p>
		You have logged out!
	</p>
{% endblock content %}

templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %}
<title>{{ user.get_full_name }}</title>
{% endblock title %}

{% block content %}
 <!--Main container. Everything must be contained within a top-level container.-->
  <div class="container-fluid">

    <!--First row (only row)-->
    <div class="row extra_margin">

      <!-- First column (smaller of the two). Will appear on the left on desktop and on the top on mobile. -->
      <div class="col-md-4 col-sm-12 col-xs-12">

          <!-- Div to center the header image/name/social buttons -->
          <div class="text-center">

              <!-- Placeholder image using Placeholder.com -->
              {%  if user.userprofile.avatar %}
              <img src="{{ user.userprofile.avatar.url }}" width="240" class="rounded">
              {% else %}
              {% if user.is_staff %}
              <img src="/media/avatar/staff-standart.jpg" width="240" class="rounded">
              {% elif user.userprofille.sex == 'M' %}
              <img src="/media/avatar/gentle-standart.jpg" width="240" class="rounded">
              {% else %}
              <img src="/media/avatar/lady-standart.jpg" width="240" class="rounded">
              {% endif %}
              {% endif %}
{#              <img src="http://via.placeholder.com/300x250" class="rounded"/>#}

              <!-- Header text (Person's name) -->
              <h2>{{ user.get_full_name }}</h2>
              <a href="{% url "accounts:EditUserProfile" pk=request.user.id %}" class="btn btn-success">Edit avatar</a>
              <br>
              <br>
              <!-- Social buttons using anchor elements and btn-primary class to style -->
              <p>
                <a class="btn btn-primary btn-xs" href="#" role="button">Facebook</a>
                <a class="btn btn-primary btn-xs" href="#" role="button">Twitter</a>
                <a class="btn btn-primary btn-xs" href="#" role="button">Instagram</a>
                <a class="btn btn-primary btn-xs" href="#" role="button">Website</a>
              </p>

          </div>

      </div> <!-- End Col 1 -->

      <!-- Second column - for small and extra-small screens, will use whatever # cols is available -->
      <div class="col-md-7 col-sm-* col-xs-*">

        <!-- "Lead" text at top of column. -->
        <h5 class="text-center text-info">USER TAPE</h5><hr>

        {% for repost in reposts %}
        <div class="card">
          <div class="card-header">
            {{ repost.content }}
          </div>
          <div class="card-body">
            <div class="row">
              <div class="col-md-10">
                <div class="card flex-md-row mb-4 box-shadow h-md-250">
                    <div class="card-body d-flex flex-column align-items-start">
                        <strong class="d-inline-block mb-2 text-primary">{{ repost.get_object_for_content_type.category.name }}</strong>
                        <h3 class="mb-0">
                          <a class="text-dark" href="{{ repost.get_object_for_content_type.get_absolute_url }}">{{ repost.get_object_for_content_type.title|truncatechars:20 }}</a>
                        </h3>
                        <div class="mb-1 text-muted">Nov 13</div>
                        <p class="card-text mb-auto">{{ repost.get_object_for_content_type.content|truncatewords:15 }}</p>
                        <a href="{{ repost.get_object_for_content_type.get_absolute_url }}">Continue reading</a>
                    </div>
                    <img class="card-img-right flex-auto d-none d-lg-block img-fluid img-preview image-preview"
                         src="{{ repost.get_object_for_content_type.image.url }}" data-holder-rendered="true"
                         alt="Responsive image">
                </div>
              </div>
            </div>
          </div>
          <div class="card-footer text-muted">
            <div class="d-flex justify-content-between bd-highlight mb-3">
              <div class="p-2 bd-highlight">{{ repost.timestamp }}</div>
              <div class="p-2 bd-highlight justify-content-end">
                <a href="#" class="like" data-id="{{ repost.pk }}" data-type="repost"><i class="far fa-thumbs-up" style="color: #00cc00"></i></a><span id="repost-liked-{{ repost.pk }}">{{ repost.get_likes }}</span>
                <a href="#" class="dislike" data-id="{{ repost.pk }}" data-type="repost" style="padding-left: 25px"><i class="far fa-thumbs-down" style="color: #a41515"></i></a><span id="repost-disliked-{{ repost.pk }}">{{ repost.get_dislikes }}</span>
              </div>
            </div>
          </div>
        </div>
        <br>
        {% endfor %}

      </div> <!-- End column 2 -->

    </div> <!-- End row 1 -->

</div> <!-- End main container -->
{% endblock content %}

{% block jquery %}
<script>
    $(document).ready(function () {
        $('.like').click(function (e) {
            e.preventDefault();
            var mark = 'L';
            var obj_id = $(this).attr('data-id');
            var model_type = $(this).attr('data-type');

            data = {
                mark: mark,
                obj_id: obj_id,
                model_type: model_type
            };

            $.ajax({
                type: "GET",
                url: "{% url 'main:user-marked-something' %}",
                data: data,
                dataType: "json",
                success: function (data) {
                    console.log(data);
                    $('#'+data.model_type+'-liked-'+data.obj_id).html(data.obj_likes);
                    $('#'+data.model_type+'-disliked-'+data.obj_id).html(data.obj_dislikes);
                }
            })
        });
        $('.dislike').click(function (e) {
            e.preventDefault();
            var mark = 'D';
            var obj_id = $(this).attr('data-id');
            var model_type = $(this).attr('data-type');

            data = {
                mark: mark,
                obj_id: obj_id,
                model_type: model_type
            };

            $.ajax({
                type: "GET",
                url: "{% url 'main:user-marked-something' %}",
                data: data,
                dataType: "json",
                success: function (data) {
                    console.log(data);
                    $('#'+data.model_type+'-liked-'+data.obj_id).html(data.obj_likes);
                    $('#'+data.model_type+'-disliked-'+data.obj_id).html(data.obj_dislikes);
                }
            })
        });
    })
</script>
{% endblock jquery %}

templates/accounts/reg_form.html
{% extends 'base.html' %}

{% block content %}
	<div class="container">
		<h1>Register</h1>
		<form method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit">Submit</button>
		</form>
	</div>
{% endblock content %}

templates/accounts/reset_password.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
	<h1>Password reset</h1>
	<p>
		Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
	</p>
	<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Reset password</button>
	</form>
</div>
{% endblock content %}

templates/accounts/reset_password_complete.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Password reset complete</h1>
    <a href="{% url 'accounts:login' %}">Log in</a>
</div>
{% endblock content %}

templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Enter new password</h1>
    <p>

    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset password</button>
    </form>
</div>
{% endblock content %}

templates/accounts/reset_password_done.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Password reset sent</h1>
    <p>
        We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

        If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.
    </p>
</div>
{% endblock content %}

templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}