accounts/urls.py
from django.contrib.auth.views import (
    LoginView,
    login,
    logout,
    password_reset,
    password_reset_complete,
    password_reset_confirm,
    password_reset_done,
)
from django.urls import path, re_path

from .views import (
    ChangePasswordView,
    EditProfileView,
    EditUserProfile,
    ProfileView,
    RegisterView,
)

app_name = "accounts"

urlpatterns = [
    re_path(r"^(?P<pk>\d+)/$", ProfileView.as_view(), name="view_profile_with_pk"),
    re_path(r"^(?P<pk>\d+)/edit$", EditUserProfile.as_view(), name="EditUserProfile"),
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", login, {"template_name": "accounts/login.html"}, name="login"),
    path("logout/", logout, {"template_name": "accounts/logout.html"}, name="logout"),
    path("edit/", EditProfileView.as_view(), name="edit_profile"),
    path("change-password/", ChangePasswordView.as_view(), name="change_password"),
    path(
        "reset-password/",
        password_reset,
        {
            "template_name": "accounts/reset_password.html",
            "post_reset_redirect": "accounts:password_reset_done",
            "email_template_name": "accounts/reset_password_email.html",
        },
        name="reset_password",
    ),
    path(
        "reset-password/done/",
        password_reset_done,
        {"template_name": "accounts/reset_password_done.html"},
        name="password_reset_done",
    ),
    re_path(
        r"reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$",
        password_reset_confirm,
        {
            "template_name": "accounts/reset_password_confirm.html",
            "post_reset_redirect": "accounts:password_reset_complete",
        },
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        password_reset_complete,
        {"template_name": "accounts/reset_password_complete.html"},
        name="password_reset_complete",
    ),
]

mainapp/urls.py
from django.urls import path, re_path

from .views import (
    ArticleDetailView,
    ArticleEditView,
    CategoryDetailView,
    CommentEditView,
    CommentSavingView,
    HotArticleImageView,
    MainListView,
    UserMarkedSomethingView,
    UserRepostArticleView,
)

app_name = "main"

urlpatterns = [
    path("add_comment/", CommentSavingView.as_view(), name="add-comment"),
    path("hot-image-view/", HotArticleImageView.as_view(), name="get-hot-image"),
    path(
        "user-repost-article/",
        UserRepostArticleView.as_view(),
        name="user-repost-article",
    ),
    path(
        "user-marked-something/",
        UserMarkedSomethingView.as_view(),
        name="user-marked-something",
    ),
    path("", MainListView.as_view(), name="home"),
    re_path(
        r"^(?P<slug>[-\w]+)/$", CategoryDetailView.as_view(), name="category-detail"
    ),
    re_path(
        r"^comment/(?P<slug>[-\w]+)/(?P<id>\d+)/edit$",
        CommentEditView.as_view(),
        name="comment-edit",
    ),
    re_path(
        r"^(?P<cat_slug>[-\w]+)/(?P<slug>[-\w]+)/$",
        ArticleDetailView.as_view(),
        name="article-detail",
    ),
    re_path(
        r"^(?P<cat_slug>[-\w]+)/(?P<slug>[-\w]+)/edit$",
        ArticleEditView.as_view(),
        name="article-edit",
    ),
    re_path(
        r"^(?P<cat_slug>[-\w]+)/(?P<slug>[-\w]+)/$",
        ArticleDetailView.as_view(),
        name="article-detail",
    ),
]

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    {% block title %}
    <title>AJAX NEWS</title>
    {% endblock title %}

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Fontawesome core CSS -->
    <link href="{% static 'font-awesome/css/fontawesome.css' %}" rel="stylesheet">
    <link href="{% static 'font-awesome/css/all.css' %}" rel="stylesheet">


    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <link href="{% static 'css/blog/blog.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/jaselnik/main.css' %}">
  </head>

  <body>

    <div class="container">
      {% block header %}
      <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">
            <a class="text-muted" href="#">Subscribe</a>
          </div>
          <div class="col-4 text-center">
            <a class="blog-header-logo text-dark" href="/">AJAX NEWS</a>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">
            <a class="text-muted" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3"><circle cx="10.5" cy="10.5" r="7.5"></circle><line x1="21" y1="21" x2="15.8" y2="15.8"></line></svg>
            </a>
            {% if request.user.is_authenticated %}
            <a class="btn btn-sm btn-outline-success" href="{% url 'accounts:view_profile_with_pk' request.user.pk %}">Profile</a>
            <a class="btn btn-sm btn-outline-secondary" href="{% url 'accounts:logout' %}">Sign out</a>
            {% else %}
            <a class="btn btn-sm btn-outline-secondary" href="{% url 'accounts:login' %}">Sign in</a>
            <a class="btn btn-sm btn-outline-primary" href="{% url 'accounts:register' %}">Sign up</a>
            {% endif %}
          </div>
        </div>
      </header>

      <div class="nav-scroller py-1 mb-2">
        <nav class="nav d-flex justify-content-between">
            {% for category in categories %}
            <a class="p-2 text-muted" href="{{ category.get_absolute_url }}">{{ category.name }}</a>
            {% endfor %}
        </nav>
      </div>
      {% endblock header %}

      {% block preview %}
      {% endblock preview%}
    </div>

    {% block content %}
    {% endblock content %}

    <footer class="blog-footer">
      <p>Blog template built for <a href="https://getbootstrap.com/">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script>window.jQuery || document.write('<script src="{% static 'assets/js/vendor/jquery-slim.min.js' %}"><\/script>')</script>
    <script src="{% static 'assets/js/vendor/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/holder.min.js' %}"></script>
    <script>
      Holder.addTheme('thumb', {
        bg: '#55595c',
        fg: '#eceeef',
        text: 'Thumbnail'
      });
    </script>
    {% block jquery %}
    {% endblock jquery %}
  </body>
</html>

templates/index.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    {% block title %}
    <title>AJAX NEWS</title>
    {% endblock title %}

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <link href="{% static 'css/blog/blog.css' %}" rel="stylesheet">
  </head>

  <body>

    {% block header %}
    <div class="container">
      <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">
            <a class="text-muted" href="#">Subscribe</a>
          </div>
          <div class="col-4 text-center">
            <a class="blog-header-logo text-dark" href="/">AJAX NEWS</a>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">
            <a class="text-muted" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3"><circle cx="10.5" cy="10.5" r="7.5"></circle><line x1="21" y1="21" x2="15.8" y2="15.8"></line></svg>
            </a>
            <a class="btn btn-sm btn-outline-secondary" href="#">Sign up</a>
          </div>
        </div>
      </header>

      <div class="nav-scroller py-1 mb-2">
        <nav class="nav d-flex justify-content-between">
            {% for category in categories %}
            <a class="p-2 text-muted" href="{{ category.get_absolute_url }}">{{ category.name }}</a>
            {% endfor %}
        </nav>
      </div>

      <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
        <div class="col-md-6 px-0">
          <h1 class="display-4 font-italic">Title of a longer featured blog post</h1>
          <p class="lead my-3">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what's most interesting in this post's contents.</p>
          <p class="lead mb-0"><a href="#" class="text-white font-weight-bold">Continue reading...</a></p>
        </div>
      </div>

      <div class="row mb-2">
        {% for article in articles %}
        <div class="col-md-6">
          <div class="card flex-md-row mb-4 box-shadow h-md-250">
            <div class="card-body d-flex flex-column align-items-start">
              <strong class="d-inline-block mb-2 text-primary">{{ article.category.name }}</strong>
              <h3 class="mb-0">
                <a class="text-dark" href="{{ article.get_absolute_url }}">{{ article.title }}</a>
              </h3>
              <div class="mb-1 text-muted">Nov 13</div>
              <p class="card-text mb-auto">{{ article.content|truncatewords:15 }}</p>
              <a href="{{ article.get_absolute_url }}">Continue reading</a>
            </div>
            <img class="card-img-right flex-auto d-none d-lg-block"
                 style="width: 200px; height: 250px;"
                 src="{{ article.image.url }}" data-holder-rendered="true">
          </div>
        </div>
        {% endfor %}
        </div>
    </div>
    {% endblock header %}

    {% block content %}
    {% endblock content %}

    <footer class="blog-footer">
      <p>Blog template built for <a href="https://getbootstrap.com/">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="{% static 'assets/js/vendor/jquery-slim.min.js' %}"><\/script>')</script>
    <script src="{% static 'assets/js/vendor/popper.min.js' %}"></script>
    <script src="{% static 'dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/holder.min.js' %}"></script>
    <script>
      Holder.addTheme('thumb', {
        bg: '#55595c',
        fg: '#eceeef',
        text: 'Thumbnail'
      });
    </script>
  </body>
</html>